In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sys

## Numpy
https://numpy.org/doc/stable/reference/index.html#reference

In [2]:
y = np.random.normal(10, 3, 10000)

In [3]:
type(y)

numpy.ndarray

In [4]:
y

array([ 8.58233323, 13.83998365,  5.24889827, ..., 10.5611802 ,
        8.16124068,  9.22500855])

In [5]:
y.shape

(10000,)

In [6]:
y.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [7]:
y.flags.owndata

True

In [8]:
y.city = "Toulouse"

AttributeError: 'numpy.ndarray' object has no attribute 'city'

In [ ]:
del y.shape

In [ ]:
y.shape

In [ ]:
y.shape = (10, 1000)

In [ ]:
y.shape = (3,3)

In [ ]:
_ = plt.hist(y, 1000)

In [9]:
# ndarray has no truth value
try:
    bool(y)
except ValueError as e:
    print("ValueError:", e)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()


In [10]:
y == 3

array([False, False, False, ..., False, False, False])

In [11]:
3 == y

array([False, False, False, ..., False, False, False])

In [12]:
3 + y

array([11.58233323, 16.83998365,  8.24889827, ..., 13.5611802 ,
       11.16124068, 12.22500855])

In [13]:
y[y>10]

array([13.83998365, 10.2647389 , 10.79713753, ..., 10.40237937,
       11.66164257, 10.5611802 ])

In [14]:
assert y.__getitem__(0) == y[0]

In [15]:
(1,2,3)[0]

1

In [16]:
# TypeError: 'tuple' object does not support item assignment
t = (1,2,3)
try:
    t[0] = 2
except TypeError as e:
    print("TypeError:",e)

TypeError: 'tuple' object does not support item assignment


In [17]:
mat = np.zeros((100,100), dtype=np.float32)
mat

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [18]:
image = np.ones((100,100), dtype=np.uint8)
image

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]], dtype=uint8)

In [19]:
image[::2, ::4] = 129
image

array([[129,   1,   1, ...,   1,   1,   1],
       [  1,   1,   1, ...,   1,   1,   1],
       [129,   1,   1, ...,   1,   1,   1],
       ...,
       [  1,   1,   1, ...,   1,   1,   1],
       [129,   1,   1, ...,   1,   1,   1],
       [  1,   1,   1, ...,   1,   1,   1]], dtype=uint8)

In [20]:
image += 140
image

array([[ 13, 141, 141, ..., 141, 141, 141],
       [141, 141, 141, ..., 141, 141, 141],
       [ 13, 141, 141, ..., 141, 141, 141],
       ...,
       [141, 141, 141, ..., 141, 141, 141],
       [ 13, 141, 141, ..., 141, 141, 141],
       [141, 141, 141, ..., 141, 141, 141]], dtype=uint8)

In [21]:
image + 340

array([[353, 481, 481, ..., 481, 481, 481],
       [481, 481, 481, ..., 481, 481, 481],
       [353, 481, 481, ..., 481, 481, 481],
       ...,
       [481, 481, 481, ..., 481, 481, 481],
       [353, 481, 481, ..., 481, 481, 481],
       [481, 481, 481, ..., 481, 481, 481]], dtype=uint16)

In [22]:
image += 340

In [23]:
image

array([[ 97, 225, 225, ..., 225, 225, 225],
       [225, 225, 225, ..., 225, 225, 225],
       [ 97, 225, 225, ..., 225, 225, 225],
       ...,
       [225, 225, 225, ..., 225, 225, 225],
       [ 97, 225, 225, ..., 225, 225, 225],
       [225, 225, 225, ..., 225, 225, 225]], dtype=uint8)

In [24]:
image.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [25]:
image.T.flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [26]:
image.T[1,2]=33
print(image.T[1,2])
print(image[2,1])

33
33


In [27]:
d = image.diagonal()
d.flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : False
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [28]:
d[::2] = 44

ValueError: assignment destination is read-only

In [29]:
square = np.array(
    [[2,7,6],
    [9,5,1],
    [4,3,8]])

In [30]:
square.dtype

dtype('int32')

In [31]:
sys.getsizeof(7)

28

In [32]:
square = np.array(
    [[2,7,6],
    [9,5,1],
    [4,3,8]],
    dtype='uint8')
square

array([[2, 7, 6],
       [9, 5, 1],
       [4, 3, 8]], dtype=uint8)

In [33]:
np.sum(square)

45

In [34]:
square.sum()

45

In [35]:
3 + square

array([[ 5, 10,  9],
       [12,  8,  4],
       [ 7,  6, 11]], dtype=uint8)

In [36]:
square[square>5]

array([7, 6, 9, 8], dtype=uint8)

In [37]:
square>5

array([[False,  True,  True],
       [ True, False, False],
       [False, False,  True]])

In [38]:
print(square)
extract = square[::2, 1::2]
print(extract)

[[2 7 6]
 [9 5 1]
 [4 3 8]]
[[7]
 [3]]


In [39]:
print(square)
extract = square[::, ::-1]
print(extract)

[[2 7 6]
 [9 5 1]
 [4 3 8]]
[[6 7 2]
 [1 5 9]
 [8 3 4]]


In [40]:
print(square)
extract = square[slice(None), slice(None,None,-1)]
print(extract)

[[2 7 6]
 [9 5 1]
 [4 3 8]]
[[6 7 2]
 [1 5 9]
 [8 3 4]]


In [41]:
slice?

Init signature: slice(self, /, *args, **kwargs)
Docstring:     
slice(stop)
slice(start, stop[, step])

Create a slice object.  This is used for extended slicing (e.g. a[0:10:2]).
Type:           type
Subclasses:     


In [42]:
square.sum(axis=0)

array([15, 15, 15], dtype=uint32)

In [43]:
squareKoRow = np.array(
    [[2,3,6],
    [9,5,1],
    [4,7,8]])

In [44]:
# sums on each column
squareKoRow.sum(axis=0)

array([15, 15, 15])

In [45]:
# sums on each row
squareKoRow.sum(axis=1)

array([11, 15, 19])

In [46]:
def isMagic(square):
    n,_ = square.shape
    sm = n*(n**2+1)//2
    return all(np.sum(square, axis=0) == sm) \
            and all(np.sum(square, axis=1) == sm) \
            and (np.sum(square.diagonal()) == sm) \
            and (np.sum(square[::-1].diagonal()) == sm) 

In [47]:
assert 15.0 == 15

In [48]:
assert isMagic(square)
assert not isMagic(squareKoRow)

In [49]:
from carremagic_ex_np import d_ca

In [50]:
{ name: isMagic(square) for name,square in d_ca.items() }

{'ca3': True,
 'ca3_no_diag': False,
 'ca3_no_lig': False,
 'ca3_no_col': False,
 'ca3_no_lig_diag': False,
 'ca4_ok': True,
 'albrecht_durer': True,
 'josep_maria_subirachs': False,
 'ca_5_semi_diabolik': True,
 'benjamin_franklin': False,
 'general_cazalas': True,
 'willem_barink_8': True,
 'willem_barink_12': True}

In [52]:
squareBF = d_ca['benjamin_franklin']

In [56]:
print(squareBF.sum(axis=0))
print(squareBF.sum(axis=1))
print(squareBF.diagonal().sum())
print(squareBF[::-1].diagonal().sum())

[260 260 260 260 260 260 260 260]
[260 260 260 260 260 260 260 260]
228
292


In [55]:
n=8
n*(n**2+1)//2

260